spring:
  kafka:
    bootstrap-servers:
      - 10.150.16.42:9092
      - 10.150.23.16:9092
      - 10.150.33.124:9092
    streams:
      cache_max_size_buffering: 100_000_000
      properties:
        commit.interval.ms: 60000
        max.request.size: 100_000_000
        num.stream.threads: 2
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
#        commit.interval.ms: 1000

sdkwriter:
  record:
    client_name_key: u1
    app_name_key: a2
    event_name_key: event_name
    key_delimiter: '_'
  input_topic: sdk-events
  output_topic: client-events
  sdk_folder: rawdata_sdk
  # window settings
  window:
    delimiter: '@'
    window_time: 300
    wait_for: 3
    writer_window: 30
    mem_limit: 1_000_000
  # client bucket map
  buckets:
    default: datavisor-clientless
    com.pagoda.buy-X8UtjLSX-DyPbJJ6f: datavisor-pagoda


aliyun:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access_id: '{cipher}8289ca814ee36c66b6f02a7471a06a1985d324e70feb9083767793837154a63fec923a52723135b1067eab0a2d598224'
  access_key: '{cipher}de206e4923b1b6b1e1bab38e3f4662505b7d224c683cadef55b176c38e86e17f0d166465c377732c66de1407b6aafce0'
